### ISSUE TITLE
[Suggestion] A couple QOL Clientside mod suggestions

### ISSUE THREAD

**Issue by SavageKiller13** [SmashingMods/CreateWithAkliz#1]
Some mods I feel were maybe forgotten or just overlooked:
1. Zoomify, Very useful for seeing things far away, found myself trying to zoom within the first few minutes playing the pack
2. Do A Barrel Roll (Can be added a little later), A clientside elytra flight mod that just changes the rendering of flying; making it more smooth and realistic. can be toggled ingame.
3. LambDynamicLights, Optional to be added; useful for those that don't want to use shaders
4. Light Overlay, Useful for seeing where mobs can spawn; can be critical for some farms and lighting up bases (especially those with caves underneath them)
5. No Telemetry, This is more of a privacy thing, might help with network usage a small bit at some points.

**Comment by TheInfamousAlk** [comment]
1. We actually considered a zoom mod, but wanted to leave it out to encourage the use of the spyglass instead, an in-world zoom device.
2. I can look into this one
3. This is reasonable but we might disable it by default to keep performance up.
4. The Haunted Bell from create does this. https://create.fandom.com/wiki/Haunted_Bell
5. No Chat Reports covers all of the functionality of this mod last I checked. We actually had this one in there but removed it since NCR was in the pack as well. 

We're trying to keep the pack as lightweight as possible for the end user and the server. Load times/performance are our top priority so we'll make all mod addition decisions with that in mind. If there is an in-game item or feature that does what an extra mod does, we will likely not add it. 

I've noted these suggestions down for the next update or two so I'll close this.
