### ISSUE TITLE
[Suggestion] Couple Serverside mods (that don't need to be added to the client)

### ISSUE THREAD

**Issue by SavageKiller13** [SmashingMods/CreateWithAkliz#2]
1. YUNG's Suite of Mods. Good for loot and promoting adventure. Mainly expands on Vanilla structures.
2. Immersive Structures (and IMST Nether edition), This may already be added but another vanilla structure mod
3. Repurposed Structures, Another Structure mod that may already be added.
4. Additional Structures, Just some more things to make the world more lively
5. Not Just Biomes, somethings that adds small intricacies to Vanilla biomes
6. Castle Dungeons, Recently went through one of these dungeons (on a private vanilla server) and they are fun.
7. When Dungeons Arise, A much bigger dungeon gen mod, could have this as a replacement for the mod above.

**Comment by TheInfamousAlk** [comment]
1. World generation mods will be a hard sell because of the performance impact if people generate chunks. But I'll still check it out. 
2. See above
3. See above
4. See above
5. This may or may not work with Terralith, which is included on the server (but not the client).
6. See above
7. This one has been known to cause a lot of lag so I'm leaning towards not using this one.
